config/routes.rb
Outhouse::Application.routes.draw do

  root to: "application#all"

  resources :events

  get "/events/c/:category" => "events#cat_list", constraints: {format: :json}

  get "*all" => "application#all"

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Geocoder::Model::Mongoid

  field :title, type: String
  field :address, type: String
  field :map_url, type: String
  field :image_url, type: String
  field :description, type: String
  field :categories, type: Array
  field :coordinates, type: Array
  field :cathash, type: Hash
  field :cat_slugs, type: Array

  geocoded_by :address

  after_validation :geocode, :set_map_url, if: :address_changed?
  after_validation :set_cat_slugs, if: :categories_changed?
  after_validation :parameterize_cathash, if: :cathash_changed?

  embeds_many :time_ranges
  embeds_one :schedule

  DefaultLocation = [37.8717443, -122.2609626]

  def as_json(options = {})
    super.merge("_id" => id.to_s, "time_ranges" => time_ranges.as_json, "schedule" => schedule.as_json)
  end

  def as_json_with_context
    as_json.merge("distance" => self.distance_from(DefaultLocation))
  end

  def self.around(time)
    time=time.to_i
    ctime = Time.at(time)
    hr = ctime.hour
    mn = ctime.min
    wday = Date::ABBR_DAYNAMES[ctime.wday].downcase

    Event.or({:time_ranges.elem_match => {:start.lt => time,
                                          :end.gt => time}},
             {:"schedule.#{wday}".elem_match => {:start.lte => hr * 100 + mn,
                                                 :end.gte => hr * 100 + mn},
              :"schedule.time_range" => nil},
             {:"schedule.#{wday}".elem_match => {:start.lte => hr * 100 + mn,
                                                 :end.gte => hr * 100 + mn},
              :"schedule.time_range.start".lte => time,
              :"schedule.time_range.end".gte => time})

    # Event.or({:time_ranges.elem_match => {:start.lt => time,
    #                                       :end.gt => time}},
    #          {:schedules.elem_match => {:"#{wday}".elem_match => {:start.lte => hr * 100,
    #                                                               :end.gte => hr * 100},
    #                                     :time_range => nil}},
    #          {:schedules.elem_match => {:"#{wday}".elem_match => {:start.lte => hr * 100,
    #                                                               :end.gte => hr * 100},
    #                                     :"time_range.start".gte => time,
    #                                     :"time_range.end".lte => time}})

  end

  def self.by_category(category)
    Event.where(:cat_slugs => /\A#{Regexp.escape(category)}\z/i)
  end

  def self.by_category_around(category, time)
    Event.by_category(category).around(time)
  end

  def parameterize_cathash
    self.cathash = cathash.reduce({}){|h,(k,v)| h[k.gsub("'","").parameterize] = v; h}
  end

  def set_cat_slugs
    self.cat_slugs = categories.map{|c| c.gsub("'","").parameterize}
  end

  def set_map_url
    self.map_url = "http://maps.google.com/?q=#{CGI.escape(address.gsub("\n", ", "))}"
  end

end

class TimeRange
  include Mongoid::Document
  #Unix time when embedded in Event
  #24x100 hour time when embedded in Schedule

  field :start, type: Integer
  field :end, type: Integer

  embedded_in :event
  embedded_in :schedule

  validates :start, presence: true
  validates :end, presence: true

  def as_json(options = {})
    {start: start, end: self.end}
  end

end

class Schedule
  include Mongoid::Document

  Date::ABBR_DAYNAMES.each do |day|
    embeds_many day.downcase.to_sym, class_name: "TimeRange"
  end

  embeds_one :time_range

  embedded_in :event

  def as_json(options = {})
    {_id: id.to_s, sun: sun.as_json, mon: mon.as_json, tue: tue.as_json, wed: wed.as_json,
     thu: thu.as_json, fri: fri.as_json, sat: sat.as_json, time_range: time_range.as_json}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :set_csrf_cookie

  def set_csrf_cookie
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :find_event!, only: [:show, :edit]

  def index
    @events = Event.all

    respond_to do |format|
      format.html
      format.json {render json: @events.map(&:as_json_with_context)}
    end
  end

  def new

  end

  def create
    @event = Event.new(event_params)
  end

  def show

    # render json: @event.to_json

    respond_to do |format|
      format.html
      format.json {render json: @event.as_json_with_context}
    end
  end

  def edit

  end

  def destroy

  end

  def cat_list
    if params[:time].present?
      @events = Event.by_category(params[:category]).around(params[:time])
    else
      @events = Event.by_category(params[:category]).around(Time.now.to_i)
    end

    respond_to do |format|
      format.json {render json: @events.map(&:as_json_with_context)}
    end
  end

  protected
  def find_event!
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :description %><br />
  <%= f.text_field :description %></div>

  <div><%= f.label :categories %><br />
  <%= f.text_field :categories %></div>

<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= link_to event.title, event_path(event) %>
  <%= event.description%>
<% end %>

app/views/events/new.html.erb
<%= form_for Event.new do |f| %>
  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :description %><br />
  <%= f.text_field :description %></div>

  <div><%= f.label :categories %><br />
  <%= f.text_field :categories %></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outhouse</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=0">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /> 
  <meta name="apple-mobile-web-app-capable" content="yes" />

  <link rel="apple-touch-icon" href="<%= image_path 'icons/AppIcon60x60@2x.png' %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/AppIcon76x76.png' %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/AppIcon60x60@2x.png' %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/AppIcon76x76@2x.png' %>">
  <link rel="shortcut icon" href="<%= image_path 'icons/AppIcon29x29@2x.png' %>">

  <link rel="apple-touch-startup-image" href="<%= image_path 'loading/iphone.png' %>" />
	<link rel="apple-touch-startup-image" href="<%= image_path 'loading/iphone5.png' %>" media="screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags unless Rails.env.staging? %>
</head>

<body style="padding:0 0 20px 0 ;height:100%" class="selector-page" ng-app="Outhouse">

<div id="fb-root"></div>

<div class="bkg"></div>


<div style="position:fixed; width:100%;height:100%;background-color:black; opacity:{{opacity.val}};"></div>


<div class="installer">
	<div style="font-size:32px;font-weight:bolder;text-align:center">Get Outhouse</div>

	<div style="font-size:24px;text-align:center">iPhone App</div>

	<img class="appicon" src="<%= image_path 'icons/AppIcon76x76@2x.png' %>" />

	<div style="margin-top:30px;font-size:16px">
		Install by tapping the <img class="appicon" src="<%= image_path 'popout.png' %>" style="margin-top:-10px" /> button,<br />and then tap "Add to Home Screen"
	</div>


	<div style="margin-top:50px;font-size:11px">
		<a href="#" onclick="$(this).closest('.installer').remove();">or continue to the web version</a>
	</div>
</div>

  <div class="container" style="padding:0px;" ng-view=""></div>


<%# yield %>

</body>
<!-- <script src="http://rawgithub.com/Ciul/angular-facebook/master/lib/angular-facebook.js"></script> -->
<%= javascript_include_tag "application" %>

<% cache_unless Rails.env.staging? do %>
<% Dir.glob(Rails.root.join('app','assets','javascripts', 'templates', '**/*.html')).each do |f| %>
<script type="text/ng-template" id="<%= f.sub("#{Rails.root.join('app', 'assets', 'javascripts', 'templates')}/", '') %>">
<%= render file: f %>
</script>
<% end %>
<% end %>
</html>